### ISSUE TITLE
Incorrect APEC version retrieved when SOXS lives in a path with an underscore

### ISSUE THREAD

**Issue by DavidT3** [jzuhone/soxs#1]
A very small and specific bug, present in spectra.py:
* When apec_root is not specified by the user, SOXS sets it automatically.
* It determines SOXS' current version of APEC by finding cfile, then splitting the string with split('_').
* Normally fine, but when in a path with underscores outside the 'apec_v3.0.9_coco.fits' name, it doesn't return the version.
* Which then means SOXS can't load the apec table, and as SOXS does this for pyXSIM as well it also breaks that.

**Comment by jzuhone** [comment]
Hi @DavidT3, thanks for this report! It seems like you have diagnosed this issue pretty well--do you mind submitting a pull request for a fix? I'd be happy to review it and merge it then.

**Comment by DavidT3** [comment]
Yeah happy to help!
