### ISSUE TITLE
Creating simulated chandra observations from a GRID file and choosing line of sight

### ISSUE THREAD

**Issue by Joshuaalbert** [jzuhone/soxs#3]
Greetings,

I'm working with Julius Donnert on a project, and we're trying to create simulated Chandra observations from gridded data.
I'm using https://github.com/jdonnert/Sph2Grid to turn Magneticum snapshots (gadgetv2) into gridded HDF5.
Is it possible to control what the viewing angle is during the observation, i.e. is it possible to choose inside SOXS, or should I rotate the gridded data for every viewing angle I want (which seems rather inefficient). I'm trying to compare the ease of use and functionality with PHOX.

Do you have a minimal example that would accomplish this simple goal from python?

Thanks in advance.

**Comment by jzuhone** [comment]
Closing because this was discussed over at pyXSIM.
