### ISSUE TITLE
APEC version

### ISSUE THREAD

**Issue by qinyuxian** [jzuhone/soxs#5]
Hi John,

As you describe, the galactic foreground component is modeled as a sum of two apec models. After I checked the spectrum, I found that the apec model used to generate the foreground is probably the version 2.0.2. However, the apec model which be used to generate the photons in step 1 is the version 3.0.9. So there are two different version apec in pyXSIM.
By the way, why the foreground use result of Chandra rather than the result of the calorimeter sounding rocket data reported in McCammon et al. (2002)?  The result of McCammon is based on high-resolution microcalorimeter. The narrow emission lines are clearly seen in the original spectrum.

Thank you.

**Comment by jzuhone** [comment]
@qinyuxian this should be fixed now, please re-open if this is still an issue.
