### ISSUE TITLE
How to fast estimate the luminosity of the halo?

### ISSUE THREAD

**Issue by qinyuxian** [jzuhone/soxs#7]
Hi John, 

Is there any approach to fast estimate the luminosity just from the parameters of the halo or subhalo? A empirical relation will also be acceptable. I don't want to waste time on calculating particle by particle or cell by cell.

Thank you and best wishes.

**Comment by jzuhone** [comment]
Hi @qinyuxian, 

You may want to check this out:

https://yt-project.org/doc/analyzing/analysis_modules/xray_emission_fields.html

that is for the stable version of yt, v3.6.1.

But if you have an SPH dataset, you might want to install yt v4.0 from source (it's in beta) and try it like this:

https://yt-project.org/docs/dev/analyzing/domain_analysis/xray_emission_fields.html

(apologies that the docs are broken on the second page, you just need to download the apec_emissivity_v3.h5 file from http://yt-project.org/data and everything should be fine)

**Comment by qinyuxian** [comment]
Hi John,

Could you tell me which specific model you used to create the cloudy_emissivity file?
I have noticed that Nelson et. al. run CLOUDY in the 'constant temperature' mode to compute ionization states.

Thank you.

**Comment by jzuhone** [comment]
@qinyuxian you should probably use the `apec_emissivity_v3.h5` file linked in the second doc, and set `table_type='apec'`, to use the AtomDB model for collisionally ionized plasma, unless you do want to assume photoionization.

**Comment by jzuhone** [comment]
Closing because this is unrelated to SOXS. Please reopen at yt or pyXSIM if you want further discussion.
